# -*- coding: utf-8 -*-
"""De zeven klasmozaïeken als rasters — bron van waarheid voor §13.10.

Elk mozaïek is 96 x 64 tesserae — 6144 steentjes:

    +----------------------------------------------+
    |  rand: 6 tesserae dik, GEGENEREERD (meander)  |
    |   +--------------------------------------+    |
    |   |  emblema: 84 x 52, MET DE HAND        |   |
    |   +--------------------------------------+    |
    +----------------------------------------------+

Zo werkte een Romeins mozaïek ook: een fijn middenstuk (emblema) in een grover veld.
Het scheelt bovendien tekenwerk — de rand is overal dezelfde en hoeft maar één keer.

Palet per mozaïek; "." is de ondergrond (de kalkmortel), niet doorzichtig.
Na een wijziging:  python3 contactblad.py   (KIJK ERNAAR)  en dan  python3 injecteer.py
"""

BREED, HOOG = 96, 64
RAND = 6
EBREED, EHOOG = BREED - 2 * RAND, HOOG - 2 * RAND      # 84 x 52

# De rand: buitenlijn, meanderband van 2, binnenlijn. Tekens verwijzen naar het palet
# van het mozaïek zelf, zodat elke rand meekleurt met zijn tafereel.
def rand_raster():
    """Geeft 32 regels van 48 tekens: de rand ingevuld, het midden als spatie."""
    r = [[" "] * BREED for _ in range(HOOG)]

    def lijn(x0, y0, x1, y1, ch):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                r[y][x] = ch

    lijn(0, 0, BREED - 1, 0, "d");  lijn(0, HOOG - 1, BREED - 1, HOOG - 1, "d")
    lijn(0, 0, 0, HOOG - 1, "d");   lijn(BREED - 1, 0, BREED - 1, HOOG - 1, "d")
    lijn(1, 1, BREED - 2, RAND - 2, "l");  lijn(1, HOOG - RAND + 1, BREED - 2, HOOG - 2, "l")
    lijn(1, 1, RAND - 2, HOOG - 2, "l");   lijn(BREED - RAND + 1, 1, BREED - 2, HOOG - 2, "l")

    # Meander (Griekse sleutel), vereenvoudigd tot blokjes van 2 op 2 — op deze
    # korrel leest dat als een echte meanderband en niet als ruis.
    for x in range(2, BREED - 3, 6):
        for dy in (1, 2):
            r[dy][x] = r[dy][x + 1] = r[dy][x + 2] = "d"
            r[HOOG - 1 - dy][x] = r[HOOG - 1 - dy][x + 1] = r[HOOG - 1 - dy][x + 2] = "d"
    for y in range(2, HOOG - 3, 6):
        for dx in (1, 2):
            r[y][dx] = r[y + 1][dx] = r[y + 2][dx] = "d"
            r[y][BREED - 1 - dx] = r[y + 1][BREED - 1 - dx] = r[y + 2][BREED - 1 - dx] = "d"

    lijn(RAND - 1, RAND - 1, BREED - RAND, RAND - 1, "d")
    lijn(RAND - 1, HOOG - RAND, BREED - RAND, HOOG - RAND, "d")
    lijn(RAND - 1, RAND - 1, RAND - 1, HOOG - RAND, "d")
    lijn(BREED - RAND, RAND - 1, BREED - RAND, HOOG - RAND, "d")
    return ["".join(rij) for rij in r]


M = {}

# ---------------------------------------------------------------- Caput 1
# CAVE CANEM — Pompeii. Zwarte waakhond aan een ketting, grommend naar links,
# met het onderschrift in de mozaïekletters van het origineel.
M["cave-canem"] = dict(
    caput=1, naam="Cave canem", bij="Pompeii · Huis van de tragische dichter",
    flavour="Pas op voor de hond. Hij ligt er al tweeduizend jaar.",
    pal=dict(d="#2a2018", l="#d9cbb0", o="#17140f", w="#f2ead8", r="#8c2f20",
             g="#9c8f78", t="#3b322a"),
    em=[
        ".............o..............o.......................................................",
        ".............oo............oo.......................................................",
        ".............ooo..........ooo......................................................o",
        "............ooooo........oooo.....................................................oo",
        "............oooooo.......oooo....................................................ooo",
        "............oooooooooo..ooooo...................................................oooo",
        "............oooooooooooooooooo................................................ooooo.",
        ".............ooooooooooooooooo..r............................................oooooo.",
        "............oooooowooooooorrrrrrr..........................................oooooooo.",
        "...........ooooowwowwooooorrrrrrr.........................................ooooooooo.",
        "..........oooooowooowooooorrrrrrr...........................o............oooooooooo.",
        "........oooooooowwowwooooorrrrrrrooooooooooooooooooooooooooooooo........ooooooooo...",
        "......oooooooooooowooooooorrrrrrrooooooooooooooooooooooooooooooooo....oooooooo......",
        "oooooooooooooooooooooooooorrrrrrroooooooooooooooooooooooooooooooooooooooooooo.......",
        "oooooooooooowooooooooooooorrrrrrrooooooooooooooooooooooooooooooooooooooooooo........",
        "wwwwwwwwwwwwwooooooooooooorrrrrrrrooooooooooooooooooooooooooooooooooooooooo.........",
        "wwwwwwwwwwwwwoooooooooooooorrrrrrrooooooooooooooooooooooooooooooooooooooo...........",
        "wwwwwwwwwwwwwoooooooooooooorrrrrrroooooooooooooooooooooooooooooooooooooo............",
        "ooooooooooooooooooooooooooorrrrrrrooooooooooooooooooooooooooooooooooooo.............",
        "ooooooooooooooooooooooooooorrrrrrroooooooooooooooooooooooooooooooooooo..............",
        "............ooooooooooooooorrrrrrrooooooooooooooooooooooooooooooooooo...............",
        "..............ooooooo....oorrroooroooooooooooooooooooooooooooooooooooooo............",
        "...........................rrooooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "..............................oooooo.....oooooo.........oooooo....oooooo............",
        "............................oooooooooo.oooooooooo.....oooooooooooooooooooo..........",
        "............................oooooooooo.oooooooooo.....oooooooooooooooooooo..........",
        "...................ggggggggggggggggggggggggggggggggggggggggggggggggggggggg..........",
        "..............ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg.....",
        "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
        "..............................................g.....................................",
        "............ttttt.ttttt.tt.tt.ttttt.......ttttt.ttttt.tt..t.ttttt.tt.tt.............",
        "............tt....tt.tt.tt.tt.tt..........tt....tt.tt.ttt.t.tt....ttttt.............",
        "............tt....tt.tt.tt.tt.tt..........tt....tt.tt.ttttt.tt....ttttt.............",
        "............tt....ttttt.tt.tt.tttt........tt....ttttt.ttttt.tttt..tt.tt.............",
        "............tt....tt.tt.tt.tt.tt..........tt....tt.tt.t.ttt.tt....tt.tt.............",
        "............tt....tt.tt..ttt..tt..........tt....tt.tt.t..tt.tt....tt.tt.............",
        "............ttttt.tt.tt...t...ttttt.......ttttt.tt.tt.t..tt.ttttt.tt.tt.............",
    ])


# ---------------------------------------------------------------- Caput 2
M["amor-dolfijn"] = dict(
    caput=2, naam="Amor op een dolfijn", bij="Romeins motief, o.a. Ostia",
    flavour="Liefde stuurt slecht. De dolfijn doet zijn best.",
    pal=dict(d="#12303a", l="#e3eef0", o="#0d1c24", w="#f7f2e4", h="#e8b9a0",
             b="#215f78", z="#b8e2ee", r="#b4463a", g="#d9a441"),
    em=[
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllolllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllglllllllllllooolllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllggggggggggglllllllloowwwolllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllgggggggggggllllllowwwwwwllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllgggggggggggglllowwwwwwwollllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllgggggggggggggoowwwwwwwwwollllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllhhhhhhhhhowwwwwwwwwwwwollllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllhhhohhhohhhlowwwwwwwwwwlllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllhhhhhhhhhlllowwwwwwwwolllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllhhhrrrhhhlllllowwwwwwolllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllhhhhhhhhhlllllloowwwwolllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllooohhhhhhholooollllowwwllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllloohoooohoooooohoollllooollllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllloohhhhoohhhhhoohhhhoolllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllloohhhhhhhohhhhhohhhhhhhoolllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllloohhhhhhhoohhhhhoohhhhhhhhoolllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllloohhhhhhhhoohhhhhhhoohhhhhhhhhollllllllllllllllllllllllll",
        "lllllllllllllllllllllllllloohhhhhhhhoohhhhhhhhhooohhhhhhhholllllllllllllllllllllllll",
        "lllllllllllllllllllllllloohhhhhhhhoohhhhhhhhhhhhozoohhhhhholllllllllllllllllllllllll",
        "llllllllllllllllllllllooohhhhhhhoozohhhhhhhhhhhhozzzoohhhholllllllllllllllllllllllll",
        "llllllllllllllllllllooohhhhhhhhoooooooooooooooooooozzzoooooollllllllllllllllllllllll",
        "lllllllllllllllllloozohhhhhhhoozzorrrrrrrrrrrrrrrrozzzzzzzzzoollllllllllllllllllllll",
        "lllllllllllllllloozoohhhhhhoozzzzorrrrrrrrrrrrrrrrozzzzzzzzzzzolllllllllllllllllllol",
        "lllllllllllllloozzoohhhhhhoozzzzoorrrrrrrrrrrrrrrroozzzzzzzzzzzoollllllllllllllloool",
        "llllllllllllloozzoohhhhhhozzzzzzoorrrrrrrrrrrrrrrroozzzzzzzzzzzzoolllllllllllloozzll",
        "lllllllllllloozzohhhhhhoozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzoollllllllloozzzlll",
        "llllllllllllozzohhhhhhoozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzolllllloozzzzzlll",
        "lllllllllllozzohhhhhhozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzollloozzzzzzolll",
        "llllllllllozzzohohhoozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzooozzzzzzzzllll",
        "lllllllllozzzzoohhoozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzoozzzzzzzzzlllll",
        "llllllllozzzoowooozzzzzzzzzzzzozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzoozzzzzzzzzzzlllll",
        "llllllloozooooowzzzzzzzzzzzzzoozzooooooooooooooooozzzzzzzzzzzzzzzzozzzzzzzzzzzolllll",
        "lllllloozoozwowzzzzzzzzzzoooollzzzzzzoollllllllllloooozzzzzzzzzzzzozzzzzzzzzzzllllll",
        "llloozzzozozzzzzzzzzzoooollllllozzzzzzzzzoolllllllllllooozzzzzzzzzozzzzzzzzzzlllllll",
        "ozzzzzzzzzzzzzzzzzooolllllllllllzzzzzzzzzolllllllllllllllooozzzzzzozzzzzzzzzzlllllll",
        "ooooooooozzozzzzooolllllllllllllozzzzzzzolllllllllllllllllllooozzzozzzzzzzzzzzllllll",
        "ozzzzzzzzzzozzoollllllllllllllllozzzzzzollllllllllllllllllllllooozozzzzzzzzzzzolllll",
        "ozzzzzzzoooooolllllllllllllllllllzzzzzllllllllllllllllllllllllllloooozzzzzzzzzzlllll",
        "lllllozzzooolllllllllllllllllllllozzollllllllllllllllllllllllllllllloooozzzzzzzzllll",
        "llllllooolllllllllllllllllllllllllzollllllllllllllllllllllllllllllllllllooozzzzzzlll",
        "zzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzzzlzzzzzoooozzzzzz",
        "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzooozzzz",
        "zzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzzzzzbzzzoooz",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    ])

# ---------------------------------------------------------------- Caput 3
M["gladiatoren"] = dict(
    caput=3, naam="Gladiatoren", bij="Zliten, Libië",
    flavour="De een had een net, de ander een zwaard. Raad wie won.",
    pal=dict(d="#3a2a18", l="#e2d4b4", o="#221a12", w="#f7f0dc", h="#c9a06a",
             r="#9e3323", b="#8a6a2a", g="#6a7a4a", z="#7c8fa0"),
    em=[
        "llllllllololoooloollololooolllllllllloolloolloollllllllllllloollooolooolooololoooool",
        "llllllllolololllolololololllllllllllloolloolloolllllllllllllolollollolllolllolooolll",
        "llllllllololoolloollololooolllllllllloolloolloollllllllllllloolllollooolollloloooool",
        "llllllllolololllololololllolllllllllloolloolloolllllllllllllolollollllololllolooolol",
        "lllllllllollooololollollooolllllllllloolloolloolllllllllllllololooolooolooollolooool",
        "lllllllllllllllllllllllllllllllllllloooooooooooolllllllllllooooooooooooollllllloolll",
        "llllllllllllllbbbbbbbbbbbllllllllllloooooooooooolllllllllllobbbbbbbbbbbollllloooooll",
        "llllllllllllllbbbbbbbbbbblllllllllllloolloolloollllllllllloobbbbbbbbbbboollllohoooll",
        "llllllllllllllbbbbbbbbbbbllllllllllllllloooollllllllllllllobbbbbbbbbbbbbolllobbbbbol",
        "lllllllllllllllohhhhhhholllllllllllllloohooolllllllllllllllllzzzzzzzzzllllllobbbbbll",
        "lllllllllllllllhoohhhoohllllllllllllloohhhoollllllllllllllllzzzzzzzzzzzlllllohhoooll",
        "llllllllllllllohoohhhooholllllllllllohhhhhoollllllllllllllllzzoozzzoozzllllohhhhholl",
        "lllllllllllllllhhhhhhhhhlllllllllloohhhhhhoollllllllllllllllzzoozzzoozzllllohhhholll",
        "lllllllllllllllohhhhhhhollllllllloohhhhhhooollllllllllllllllzzzzzzzzzzzlllohhhhholll",
        "lllllllllllllllohhooohhollllllllohhhhhhhooooolllllllllllllllzzzzzzzzzzzlloohhhhholll",
        "llllllllllllllllohhhhhollllllloohhhhhhhollloollllllllllolllllzzzzzzzzzlllohhhhhoolll",
        "llllllllllllllllllooolllllllloohhhhhhholllloollloooooooolllllzzzzzzzzzllohhhhhhollll",
        "llllllllllllllllllllllllllllohhhhhhhholllloooooooooooobollllllzzzzzzzllohhhhhholllll",
        "lllllllllllloooooooooooooooohhhhhhhhollllloooooobbbbbbbolllllllllzlllloohhhhhoolllll",
        "llllllllllloooooooooooooooohhhhhhhoobollllobbbbbbbbbobbollllllllllllllohhhhhhollllll",
        "llllllllllohhhohhhhhhhhhohhhhhhhhoobbollllobboooooooobbolloooooooooooohhhhhholllllll",
        "lllllllllohhhhhohhhhhhhohhhhhhhhobbboollllobbooggggggbbollooooooooooohhhhhhollllllll",
        "lllllllzzhhhhhhohhhhhhhohhhhhhoooollllllllobbogggggggbbollohhhhhhhhhohhhhhoollllllll",
        "llllllzohhhhhhhohhhhhhhohhhhhoolllllllllllobbogggggggbbollohhhhhhhhhohhhhholllllllll",
        "lllzzzozzhhhhhohhhhhhhhhohhholllllllllllllobbogggzgggbboloohhhhhhhhhhohhhollllllllll",
        "llzllozhhhhhhohhhhhhhhhhhooollllllllllllllobbogzzzzzgbbolohhhhhhhhhhhhooolllllllllll",
        "zzzzzzzzzhhhohhhhhhhhhhhhhhollllllllllllllobbogzzzzzgbbolohhhhhhhhhhhhhholllllllllll",
        "zzzzzzzhhhhohhhhhhhhhhhhhhhollllllllllllllobbogzzzzzgbbooohhhhhhhhhhhhhhoollllllllll",
        "zzzzzzzzzhoohhhhhhhhhhhhhhholllllllllllllloobbgzzzzzgobboohhhhhhhhhhhhhhoollllllllll",
        "zzzzzzzhhooohhhhhhhhhhhhhhhoollllllllllllllobbgzzzzzgobboohhhhhhhhhhhhhhoollllllllll",
        "zzzzzzzzzlooooooooooooooooooollllllllllllllobbgggzgggobboohhhhhhhhhhhhhhhollllllllll",
        "zzzzzzzoolorrrrrrrrrrrrrrrrrollllllllllllllobbgggggggobboooooooooooooooooollllllllll",
        "zzzzzzzzzlorrrrrrrrrrrrrrrrrollllllllllllllobbgggggggobborrrrrrrrrrrrrrrrollllllllll",
        "zzzzzzzlllorrrrrrrrrrrrrrrrrollllllllllllllobbgggggggobborrrrrrrrrrrrrrrrollllllllll",
        "zzzzzzzzzoorrrrrrrrrrrrrrrrroolllllllllllllobbggggggoobborrrrrrrrrrrrrrrroolllllllll",
        "zzzzzzzlloorrrrrrrrrrrrrrrrroolllllllllllllobboooooooobborrrrrrrrrrrrrrrroolllllllll",
        "zzzzzzzllooooooooollooooooooollllllllllllllobbbbbbbbbbbborrrrrrrrrrrrrrrroolllllllll",
        "zzzzzzzllohhhhhhhollohhhhhhhhllllllllllllllobbbbbbbooooooooooooollooooooooolllllllll",
        "zzzzzzzllhhhhhhhholllhhhhhhhhollllllllllllloooooooooooooohhhhhhollohhhhhhhhlllllllll",
        "zzzzzzzllhhhhhhhholllohhhhhhhollllllllllllloooooooollllhhhhhhhhollohhhhhhhhlllllllll",
        "zzzzzzzllhhhhhhhholllohhhhhhhhlllllllllllllllllllllllllhhhhhhhholllhhhhhhhhollllllll",
        "llllllllohhhhhhhhlllllhhhhhhhholllllllllllllllllllllllohhhhhhhhllllohhhhhhhollllllll",
        "llllllllohhhhhhhhlllllohhhhhhholllllllllllllllllllllllohhhhhhhhllllohhhhhhhhllllllll",
        "llllllllohhhhhhhhlllllohhhhhhhhlllllllllllllllllllllllohhhhhhhhlllllhhhhhhhholllllll",
        "ooooooooohhhhhhhooooooohhhhhhhhoooooooooooooooooooooooohhhhhhhoooooohhhhhhhhoooooooo",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    ])

# ---------------------------------------------------------------- Caput 4
M["medusa"] = dict(
    caput=4, naam="Medusa", bij="Romeins afweermasker",
    flavour="Blijf kijken. Dat is precies het idee.",
    pal=dict(d="#1c2a24", l="#dcd2bc", o="#14201c", w="#f4ecd8", h="#e0c39a",
             g="#4a7a52", z="#7fb08a", r="#9e3323", b="#2f4a40"),
    em=[
        "dddddddddddddddddddddddddzzdddddgggdddddzdddgggddddddddddddddddddddddddddddddddddddd",
        "ddddddddddddddddddddddddzzzdddddgggddddzzzddggdddddzdddddddddddddddddddddddddddddddd",
        "dddddddddddddddddddddddddzzddddddgdddddzzzddddddddzzzddddddddddddddddddddddddddddddd",
        "ddddddddddddddddddddddddddddddddddddddggggddddddddzzzddddddddggddddddddddddddddddddd",
        "dddddddddddddddddddddgggdddddddddzzdddgggdddddddddddddddgdddgggddddddddddddddddddddd",
        "dddddddddddddddddddddgggzdddddddzzzzdddddddddddggdddddzgggddzggdddddzddddddddddddddd",
        "ddddddddddddddzzzdddddzzzdddddddzzzzdddddddzddggggdddzzgggddzzzddddzzzdddddddddddddd",
        "ddddddddddddddzzzddddddzdddddggddzzdddddddzzzdggggdddzzzgddddzzdddddzzdddddddddddddd",
        "dddddddddddddddzddddddddddddggggzzdddggdddzzzzgggdddddzddddddddddddddddddddddddddddd",
        "dddddddddddddddddddggddddddddgggzzddggggddzzzggddddddddddddddddddgdddddddddddddddddd",
        "ddddddddddddddddddggggddddddddgzzzddggggzzzggggddzddddddddddddddgggddddddddddddddddd",
        "dddddddddddddddddddggddddzzddgggzddddgggggzggggzzzzddgggdzzzddddgggddddddddddddddddd",
        "ddddddddddddddddddddddddzzzzggggddddgggggggggggggzzzggggzzzzdddddgdddddddddddddddddd",
        "dddddddddddddddddzzzgdddzzzzzgggdgggggggggggggggggggdgggzzzzdddggdzzdddddddddddddddd",
        "dddddddzzzggdddddzzzggdddzzdzzzzzgggggggggggggggggggdzzzzdddddgggzzzzddzzddddddddddd",
        "dddddddzzzggdddddzzzgggdddddzzzgggggggghhhhhhhggggggggzzzdddddgggzzzddzzzzdddddddddd",
        "ddddddddddddddddddddggddddddddgggggghhhhhhhhhhhhhggggggzddddddddddzddggzzddddddddddd",
        "dddddddddddddddddddzzzddddddddggggghhhhhhhhhhhhhhhgggggddddddddddddddgggddddgddddddd",
        "dddddddddddddddddddzzzzgdddddggggghhhhhhhhhhhhhhhhhgggggdddzzzddddddddggdddgggdddddd",
        "dddddddddzzzddddggdzzzggddddgggooooooooooooooooooooooooggdzzzzgggddddddddddgggdddddd",
        "dddddddddzzzdddggggdggggddddgggooooooooooooooooooooooooggddzzgggggdddddddddddddddddd",
        "dddddddddddddddggggddggdddddgggghhwwwwwhhhhhhhwwwwwhhggggdddzdgggddddzzzdddddddddddd",
        "ddddddddddddddddggdddzzzzddgggghhwwooowwhhhhhwwooowwhhggggdddddgddzzdzzzzddddddddddd",
        "dddddddddddgdzzdddddzzzzzddgggghwwwooowwwhhhwwwooowwwhggggdddddddzzzzdzzdddddddzzddd",
        "ddddddddddgggzzddddddzzzzddgggghhwwooowwhhhhhwwooowwhhggggdddddddzzzgggddddddddzzddd",
        "ddddddddddgggzzdddddddzddddggghhhhwwwwwhhhbhhhwwwwwhhhhgggddddddddzggggddddddddddddd",
        "dddddddddddgdddggzzdddddddggggghhhhhwhhhhhbhhhhhwhhhhhgggggdddddddddgggzzddddddddddd",
        "ddddzzddddddddggggzzdddddddggghhhhhhhhhhhbbbhhhhhhhhhhhgggddddddddddddzzzgdddddddddd",
        "ddddzzddddddddggggzzddddddddghhhhhhhhhhhhbbbhhhhhhhhhhhhgddddzzdddddddzzgggddddddddd",
        "dddddddddddddddgdzzdddddddddhhhhhhhhhhhhhbbbhhhhhhhhhhhhhdddzzzzdddgggddgggddddddddd",
        "ddddddddddddddzddddggggdddddhhhhhhhhhhhhbbbbbhhhhhhhhhhhhdddzzzzdddgggdddddddddddddd",
        "dddddddggddddzzzdddggggdzdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddzzzzdddgggdddddddddddddd",
        "dddddddgggdddzzzdddggggzzzdddhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddgggzdddgddddddddddddddd",
        "dddddddggdddddzdddddddzzzzzdddhhhhhhhhhhhhhhhhhhhhhhhhhddddddggzzzzddddddzzddddddddd",
        "dddddddddddddddddddddddzzzddddhhhhhhrrrrrrrrrrrrrhhhhhhddddddggzzzzdddddzzzzdddddddd",
        "dddddddddddddgggdddddddddddddddhhhhhooooooooooooohhhhhddddddddgzzzdddddddzzddddddddd",
        "dddddddddddzzzggdddgggddddddddddhhhhhrrrrrrrrrrrhhhhhddddddddddgggddddddddddzzzddddd",
        "dddddddddddzzzggdzzzggdddddddzzzzhhhhhhhhhhhhhhhhhhhzzzzdddzzddggzzddddddggdzzzddddd",
        "ddddddddddddzddddzzzggddzzzddzgzzddhhhhhhhhhhhhhhhddzzggddzzzzdgzzzzddddgggddddddddd",
        "dddddddddddddddddzzzdddzzzzdggggzddzzhhhhhhhhhhhddddzggggdzzzzddzzzzdddddggddddddddd",
        "ddddddddddddddddddddddddzzzdggggdddzzzzdddhzzzdddddddggggddzzzdddddddddddddddddddddd",
        "dddddddddddddddddddddddddddddgggdddzzzzgggzzzzggggddzzzggddddddddddddddddddddddddddd",
        "dddddddddddddddddddggggddddddddddddzzzdggggzzzggggdzzzzdddddddgggddddddddddddddddddd",
        "dddddddddddddddddddggggddddddddddddddddzzzgdddggggdzggggddddddgggdddddzzdddddddddddd",
        "dddddddddddddzzzddddggddddddzzzdddgggddzzzzdddddddddggggddddddgggdddddzzzddddddddddd",
        "dddddddddddddzzzddddddddddddzzzzddgggddzzzzddddddddddggdddddddddddddddzzdddddddddddd",
        "dddddddddddddddddddddddzzzddgggdddgggdddddddddddzzzddddddddzzzdggddddddddddddddddddd",
        "dddddddddddddddddddddgggzzddgggdddddddddddddddddzzzddddddddzzzgggddddddddddddddddddd",
        "dddddddddddddddddddddggdzdddgggddddddddddddgggddzzzdddddddddzddggddddddddddddddddddd",
        "ddddddddddddddddddddddddddddddddddzzdddddddgggdddddddddddddddddddddddddddddddddddddd",
        "ddddddddddddddddddddddddddddddddddzzzddddddgzzzddddddggddddzzddddddddddddddddddddddd",
        "ddddddddddddddddddddddddddddddddddzzddddggddzzzdddddgggdddzzzddddddddddddddddddddddd",
    ])

# ---------------------------------------------------------------- Caput 5
M["skelet"] = dict(
    caput=5, naam="Het skelet met de wijnkruiken", bij="Pompeii, memento mori",
    flavour="Hij bedient nog altijd. Drinken doet hij niet meer.",
    pal=dict(d="#241f1a", l="#e6dcc6", o="#16120e", w="#f6f0e0", h="#b9ae94",
             r="#8c2f20", g="#7a6a52"),
    em=[
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllolllllllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllllooooooollllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllooooooooolllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllooowwwwwooollllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllooowwwwwwwooolllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllloowwwwwwwwwoolllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllloowwowwwwwowwoollllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllloowooowwwooowoollllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllooooooowooooooollllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllowwooowwwooowwollllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllloowwowwwwwowwoollllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllowwwwwowwwwwolllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllowwwwwowwwwwolllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllowwwooowwwollllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllowwwwwwwolllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllooooooooooollllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllolololololllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllllllooollllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllollllllooollllllolllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllooooooooooooooooooooooollllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllooooooooooooooooooooooooooooolllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllloooooooooolllllooollllloooooooooolllllllllllllllllllllllll",
        "lllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooollllllllllllllllllllll",
        "lllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllll",
        "lllllllllllllllllllloooooooolllllllllllllooollllllllllllloooooooolllllllllllllllllll",
        "llllllllllllllllllooooooolllllooooooooooooooooooooooooolllllooooooolllllllllllllllll",
        "llllllllllllllllloooooolllllllooooooooooooooooooooooooollllllloooooollllllllllllllll",
        "llllllllooooooolooooollllllllllllllllllllooollllllllllllllllllllooooolooooooolllllll",
        "lllllllloooooooooooolllllllllllooooooooooooooooooooooollllllllllloooooooooooolllllll",
        "llllllllooooooooooollllllllllllooooooooooooooooooooooollllllllllllooooooooooolllllll",
        "llllllooooooooooollllllllllllllllllllllllooollllllllllllllllllllllllooooooooooolllll",
        "llllloorrrrrrrrrollllllllllllllllooooooooooooooooooollllllllllllllloorrrrrrrrrolllll",
        "llllooorrrrrrrrrollllllllllllllllooooooooooooooooooollllllllllllllooorrrrrrrrrolllll",
        "llloooorrrrrrrrrollllllllllllllllllllllllooollllllllllllllllllllloooorrrrrrrrrolllll",
        "llloolorrrrrrrrrollllllllllllllllllllllllooollllllllllllllllllllloolorrrrrrrrrolllll",
        "llooolrrrrrrrrrrrllllllllllllllllllllllllooollllllllllllllllllllooolrrrrrrrrrrrlllll",
        "looollrrrrrrrrrrrllllllllllllllllooooooooooooooooooolllllllllllooollrrrrrrrrrrrlllll",
        "lloooorrrrrrrrrrrollllllllllllllloowwwwwwwwwwwwwwwoolllllllllllloooorrrrrrrrrrrollll",
        "lllooorrrrrrrrrrrollllllllllllllllowwwwwwwwwwwwwwwollllllllllllllooorrrrrrrrrrrollll",
        "lllooorrrrrrrrrrrollllllllllllllllowwwwwwwwwwwwwwwollllllllllllllooorrrrrrrrrrrollll",
        "llllooorrrrrrrrrrolllllllllllllllloowwowwwwwwwowwoolllllllllllllllooorrrrrrrrrrollll",
        "lllllorrrrrrrrrrrolllllllllllllllllowooowwwwwooowolllllllllllllllllorrrrrrrrrrrollll",
        "llllllllllllllllllllllllllllllllllllooooolllooooolllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllgggggggggoooogggggoooogggggggggllllllllllllllllllllllllll",
        "lllllllllllllllllllggggggggggggggggooooogggggoooooggggggggggggggggllllllllllllllllll",
        "llllllllllllllllgggggggggggggggggggoooogggggggooooggggggggggggggggggglllllllllllllll",
        "lllllllllllllllllllgggggggggggggggooooogggggggooooogggggggggggggggllllllllllllllllll",
        "lllllllllllllllllllllllllllgggggggoooogggggggggoooogggggggllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllloooollllllllloooolllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllooolllllllllllooolllllllllllllllllllllllllllllllll",
    ])

# ---------------------------------------------------------------- Caput 6
M["nijlscene"] = dict(
    caput=6, naam="Nijlscène", bij="Palestrina, Nijlmozaïek",
    flavour="Krokodil één, nijlpaard nul.",
    pal=dict(d="#173028", l="#e0d6ba", o="#12201a", w="#f4ecd8", h="#c98f4a",
             g="#4a7a3a", z="#8fbf6a", b="#3f7fa6", r="#9e4a2a", p="#7a5a8a"),
    em=[
        "llzzzzzzzzzlzzzzzzzzzlllllllllllllllllllllllllllllllllllllllllllllzzzzzzzzzzzzzzzzzl",
        "lzzzlzzzlzzzzzlzzzlzzzlllllllllllllllllllllllllllllllllllllllllllzzzlzzzlzzzlzzzlzzz",
        "zzzzzlllzzzzzzzlllzzzzzlllllllllllllllllllllllllllllllllllllllllzzzzzlllzzzzzlllzzzz",
        "lzzzlllglzzzzzlllglzzzlllllllllllllllllllllllllllllllllllllllllllzzzlllglzzzlllglzzz",
        "llllllggglllllllggglllllllllllllllllllllllllllllllllllllllllllllllllllggglllllggglll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "llllllggllllllllggllllllllllllllllllllllllllllllllllllllllllllllllllllggllllllggllll",
        "lllllggglllllllggglllllllllllllllllllllllllllllllllllllllllllllllllllggglllllgggllll",
        "ooooogggooooooogggooooooooooooooooooooooooooooooooooooooooooooooooooogggooooogggoooo",
        "oooooogooooooooogooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooogooooo",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboooooooooooppppppppppooobbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbooopppopppppppppppppppooobbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbooooooppppwoopppppppppppppppppoobbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbooorrrrrrrrwowoppppppppppppppppppooobbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbborwrrwrrrrrrwoopppppppppppppppppppooobbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbborrrrrrrrrroooopppppppppppppppppppooobbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbopppppppppppopppppppppppppppppppooobbb",
        "bbbbbbbbbbbbbbbbbbbbbbobbbbobbbbobbbbobbbbobbbopppppppppppopppppppppppppppppppoobbbb",
        "bbbbbbbbbbbbbbbbbbbbbbgbbbogobbbgbbbogobbbgbbbogobbbooppppppppppppppppppppppppoobbbb",
        "zzzbzzzzzbzzzzzbzzzzzgggzzgggoogggoogggoogggoogggzzggooppppppppppppppppppppppooozbbb",
        "zzzzzzzzzzzzzzzzzzzzogggooggggogggogggggogggoggggoogggoopppppppppppppppppppppoozzzzb",
        "zzzbzzzzzbzzzzzbzwowooooggggggggggggggggggggggggggggooooooooooooooooooooooooooozzbbb",
        "bbbbbbbbbbbbbbbbwooowggggggggggggggggggggggggggggggggggoooobbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbooooowowggggggggggggggggggggggggggggggggggggggoooobbbbbbbbbbbbbbbbbbbbbb",
        "bbooooggggggggggogggggggggggggggggggggggggggggggggggggggggggggooobbbbbbbbbbbbbbbbbbb",
        "bbogggggggggggggogggggggggggggggggggggggggggggggggggggggggggoogooobbbbbbbbbbbbbbbbbb",
        "bbogggggggggggggoggggggggggggggggggggggggggggggggggggggggggoggggggoobbbbbbbbbbbbbbbb",
        "bboggggggggggooooggggggggggggggggggggggggggggggggggggggggggoggggggggooobbbbbbbbbbbbb",
        "bbbwbbwbbwggwggggggggggooogggggggggggggooogggggggggoooggggogggggggggggooobbbbbbbbbbb",
        "bbbbwbbwbowggwggogggggogggogggggggggggogggogggggggogggoggggogggggggggggggooobbbbbbbb",
        "bbooogggggggggggogggggogggooggggggggggogggooggggggogggoogggogggggggggggggggoobbbbbbb",
        "bbogggggggggggggogggggoggggooooooooooooggggooooooooggggoooggoogggggggggggggggobbbbbb",
        "bbogggggggggggoooggooooogggoobbbbbbbbboogggoobbbbboogggoobooooooooggggggggggggobbbbb",
        "bzzzzzbzzzzzooooooozzzzoggggozbzzzzzbzzoggggozzzbzzoggggozzzbzzzzzoooogggggggggozzzz",
        "zzzzzzzzzzzzzzzzzzzzzzzoogggozzzzzzzzzzoogggozzzzzzoogggozzzzzzzzzzzzzooogggggggoozz",
        "bzzzzzbzzzzzbzzzzzbzzzzzoggggobzzzzzbzzzoggggozzbzzzoggggozzbzzzzzbzzzzzbooggggggooz",
        "bbbbbbbbbbbbbbbbbbbbbbbbbogggobbbbbbbbbbbogggobbbbbbbogggobbbbbbbbbbbbbbbbboogggggoo",
        "bbbbbbbbbbbbbbbbbbbbbbbbbogggobbbbbbbbbbbogggobbbbbbbogggobbbbbbbbbbbbbbbbbboogggggo",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbooobbbbbbbbbbbbbooobbbbbbbbbooobbbbbbbbbbbbbbbbbbbbboogggg",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbboogo",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbooo",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    ])

# ---------------------------------------------------------------- Caput 7
M["alexander"] = dict(
    caput=7, naam="Het Alexandermozaïek", bij="Pompeii, Huis van de Faun",
    flavour="Dareios keert zijn wagen. Alexander niet.",
    pal=dict(d="#2a2018", l="#ddceb0", o="#1a1410", w="#f2ead8", h="#b98a4a",
             r="#8c2f20", b="#8a6a2a", z="#6a6a7a", g="#4a5a3a"),
    em=[
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllolllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllzzolll",
        "llllzzlllllllzzlllllllzzlllllllzzlllolllzzlllllllzzlllllllzzlllllllzzlllllllzzzzzzoo",
        "llllzzlllllllzzlllllllzzlllllllggggggggggglllllllzzlllllllzzlllllllzzlllllllzzzzzzzo",
        "llllzzzllllllzzzllllllzzzllllllgggggggggggzllllllzzzllllllzzzllllloooollllllzozzzzll",
        "lllllzzlllllllzzlllllllzzlllllgggggggggggggooooollzzlllllllzzllloohhhholollooozzolll",
        "lllllzzzllllllzzzllllllzzzllllllohhhhhhhozzoooooooooollllllzzzoohhhhhholbooooozzllll",
        "llllllzzlllllllzzlllllllzzllllllohhhhhhholzooooooooooolllllloohhhhhhhhoooooollzzllll",
        "llllllzzzllllllzzzllllllzzzlllllohhhhhhholzzzlooooooooollloohhhhhhhhhooooobbllzzzlll",
        "lllllllzzlllllllzzlllllllzzlllllohhhhhhhollzzllllooooooooohhhhhhhhhooooobbbbollzzlll",
        "lllllllzzzllllllzzzllllllzzzlllllhhhhhhhlllzzzllllllooohhhhhhhhhhooooobbboooollzzzll",
        "llllllllzzlllllllzzlllllllzzllllllhhhhhlllllzzlloooohhhhhhhhhhhooooobbwbbbbbolllzzll",
        "llllllllzzzllllllzzzllllllzzzloooooohooooooloooohhhhhhhhhhhhoooooobbbwowbbboolllzzzl",
        "lllllllllzzlllllllzzlllllllzzooooooooooooooohhhhhhhhhhhhhhoooooobbbbbbwbbbbolllllzzl",
        "lllllllllzzzllllllzzzllllllzoohoooooooooohhhhhhhhhhhhhhhoooooboobbbbbbbbbbbolllllzzz",
        "llllllllllzzlllllllzzllllllohhhhoobbbbbohhhhhhhhhhhhhhoooooobbobbbbbbbbbbbbollllllzz",
        "llllllllllzzlllllllzzzllloohhhhhhobbbbbohhhhhhhhhhhoooooooobbboooobbbbbbbbbzllllllzz",
        "llllllllllzzzlllllllzzlloohhhhhhoobbbbbohhhhhhhoooooooooobbbbbbbbbbboooobbozllllllzz",
        "lllllllllllzzlllllllzzlohhhhhhhoobbbbbbbohhhooooooooooobbbbbbbbbbbbbolllllzzlllllllz",
        "lllllllllllzzzllllllzoohhhhhhhoobbbbbbbbbooolloooooloobbbbbbbbbbbbbollllllzzzllllllz",
        "llllllllllllzzlllllloohhhhhhhoobbbbbbbbbbbooooooozoobbbbbbbbbbbbbbozlllllllzzlllllll",
        "llllllllllllzzzlllllohhhhhhoooobbbbbbbbbbbooooolzoobbbbbbbbbbbbbboozzllllllzzzllllll",
        "lllllllllllllzzllllohhhhhhooloobbbbbbbbbooooolloobbbbbbbbbbbbbbboolzzlllllllzzllllll",
        "lllllllllllllzzzllllohhhhollooobbbbbbbbbooooolobbbbbbbbbbbbbbbbolllzzzllllllzzzlllll",
        "llllllllllllllzzlllloohoolllorrrrrrrrrrrrrrroobbbbbbbbbbbbbbbbolllllzzlllllllzzlllll",
        "llllllllllllllzzzlllllozzzlloooooooooooooooooobbbbbbbbbbbbbboollllllzzzllllllzzzllll",
        "lllllllllllllllzzloooooooooooooobbbbbbbbbbbbbobbbbbbbbbbbbboozlllllllzzlllllllzzllll",
        "lllllllllllllllzzoooobbbbbbbbbbbbbbbbbbbbbbbobbbbbbbbbbbbboozzzllllllzzzllllllzzzlll",
        "lllllllllllllllooooobbbbbbbbbbbbbbbbbbbbbbbbbobbbbbbbbbbboollzzlllllllzzlllllllzzlll",
        "llllllllllllloooooobbbbbbbbbbbbbbbbbbbbbbbbbbobbbbbbbbbbollllzzzllllllzzzllllllzzzll",
        "llllllllllloooooooobbbbbbbbbbbbbbbbbbbbbbbbbbobbbbbbbbbollllllzzlllllllzzlllllllzzll",
        "llllllllooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbobbbbbbboollllllzzlllllllzzlllllllzzll",
        "lllllloooooooooooobbbbbbbbbbbbbbbbbbbbbbbbbbbbbooobooooollllllllllllllllllllllllllll",
        "lllllooooooooooooooooobbbbbooobbbbbbbbbbbbbooobbbbooooooolllllllllllllllllllllllllll",
        "lllloooooooollllloobbbobbbobbbobbbbbbbbbbbobbbobbbobbbooolllllllllllllllllllllllllll",
        "lllloooooolllllllobbbbbobobbbbbobbbbbbbbbobbbbbobobbbbbollllllllllllllllllllllllllll",
        "lllooooolllllllllobbbbbobobbbbbobbbbbbbbbobbbbbooobbbbbollllllllllllllllllllllllllll",
        "llloooolllllllllobbbbbboobbbbbbooooooooooobbbbbboobbbbbbolllllllllllllllllllllllllll",
        "llloooolllllllllobbbbbolobbbbbolllllllllllobbbbbolobbbbbolllllllllllllllllllllllllll",
        "lloooolllllllllobbbbbboobbbbbbolllllllllllobbbbbboobbbbbbollllllllllllllllllllllllll",
        "llooollllllllllobbbbbolobbbbbolllllllllllllobbbbbolobbbbbollllllllllllllllllllllllll",
        "loooolllllllllobbbbbboobbbbbbolllllllllllllobbbbbboobbbbbbolllllllllllllllllllllllll",
        "looollllllllllobbbbbolobbbbbolllllllllllllllobbbbbolobbbbbolllllllllllllllllllllllll",
        "ooooooooooooooobbbbbooobbbbbooooooooooooooooobbbbbooobbbbboooooooooooooooooooooooooo",
        "hhhhhhhhhhhhhobbbbbohobbbbbohhhhhhhhhhhhhhhhhobbbbbohobbbbbohhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhoobbboohoobbboohhhhhhhhhhhhhhhhhoobbboohoobbboohhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhooboohhhooboohhhhhhhhhhhhhhhhhhhooboohhhooboohhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhooohhhhhooohhhhhhhhhhhhhhhhhhhhhooohhhhhooohhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
        "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    ])

# ---------------------------------------------------------------- slotpaneel
M["lupa"] = dict(
    caput=0, naam="De wolvin", bij="Romulus en Remus — het slotpaneel",
    flavour="Alle zeven af. Rome is gesticht.",
    pal=dict(d="#2a2018", l="#e0d4b6", o="#17130e", w="#f4ecd8", h="#b98a5a",
             r="#8c2f20", g="#8a7a5a"),
    em=[
        "lllllllollllllllolllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllohhllllllhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllhhhollllhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllhhhhooohhhhlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllohhhhhhohhhhollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllllohhhhhhohhhllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllohhhhhhhhholllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllloohhhhhhhholllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "ooohhhhoohhhhoohhollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "ohhhhhhoohhhhoohoollllllllllolllllolllllolllllolllllolllllolllllllllllllllllllllllll",
        "oooooooohhhhhhhhoholllllllllhlllllhlllllhlllllhlllllhlllllhlllllllllllllllllllllllll",
        "ohhhhhhohhhhhhhohhholllllllhhhlllhhhlllhhhlllhhhlllhhhlllhhhlllllllllllllllooollllll",
        "ohhhhoooohhhhhoohhhhoollllohhholohhholohhholohhholohhholohhholllllllllllloohhhooolll",
        "lllllllllooooohhhhhhhoolllllllllllllllllllllllllllllllllllolllllllllllloohhhhhhhoool",
        "lllllllllllohhhhhhhhhhhoooooooooooooooooooooooooooooooooooooolllllllloohhhhhhhhhhhho",
        "llllllllllllohhhhhhhhhhhooooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhooooollllooohhhhhhhhhhhhhh",
        "lllllllllllloohhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoooooloohhhhhhhhhhhhhhhh",
        "lllllllllllllohhhhhhhhhhhhhoohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoooohhhhhhhhhhoohhhhhh",
        "lllllllllllllloohhhhhhhhhhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhohhhhhhhhhhhoolooooho",
        "llllllllllllllloohhhhhhhhhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhohhhhhhhhhoolllllllol",
        "lllllllllllllllllohhhhhhhhhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhohhhhhhhhhoollllllllll",
        "llllllllllllllllllohhhhhhhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhohhhhhhoollllllllllll",
        "llllllllllllllllllooohhhhhhhohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhohhhhhoolllllllllllll",
        "lllllllllllllllllllooohhhhhoohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoohoolllllllllllllll",
        "lllllllllllllllllllllooohooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhooooolllllllllllllll",
        "llllllllllllllllllllllooooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhooooolllllllllllllllll",
        "llllllllllllllllllllllloohhhhohhhhohhhhohhhhhhhhhhhhohhhhohhooohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhoooooohhhhoooooooooooooohhhhoooooohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhollllohhhhollllllllllllohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhollllohhhhollllllllllllohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhollllohhhhollllllllllllohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhollllohhhhollllllllllllohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhollllohhhholollllllllllohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhorollloooohoorollllooollohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhorrrollorrroorrrollorrrolohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhorrroorrrrroorrroorrrrroohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhorrroorrrrroorrroorrrrroohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhorrrorrrrrolorrrorrrrroohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhoorrrorrrooloorrrorrrolohhhhollllohhhhollllllllllllllll",
        "llllllllllllllllllllllllohhhhoorrrooooooolorrrooooooohhhhollllohhhhollllllllllllllll",
        "lllllllllllllllllllllloooooooooorrrorrrroolorrrorrrroooooooooooooooooollllllllllllll",
        "lllllllllllllllllllllloooooooooooroorrrrrolooroorrrrrooooooooooooooooollllllllllllll",
        "llllllllllllllllllllllooooooooooooorrrrrroggooorrrrrrooooooooooooooooollllllllllllll",
        "lllllllllllllllggggggggggggggggorrrrrrrrrogorrrrrrrrroggggggggggggggggllllllllllllll",
        "llllllllllllgggggggggggggggggggorrrrrrrrrogorrrrrrrrroggggggggggggggggggglllllllllll",
        "lllllllllllllllgggggggggggggggggggggggggggggggggggggggggggggggggggggggllllllllllllll",
        "llllllllllllllllllllllllggggggggggggggggggggggggggggggggggggglllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    ])
