# -*- coding: utf-8 -*-
"""De 20 tesserae als 16x16 rasters — bron van waarheid voor de sprites in de app.

Palet: o=omtrek  s=schaduw  b=basis  a=accent  h=hoogsel  e=donker (oog)  .=doorzichtig
Na een wijziging:  python3 contactblad.py   (kijk ernaar!)  en dan  python3 injecteer.py
"""

W = 16
S = {}

S["tessera"] = dict(pal=dict(o="#6b4a12", s="#a87a28", b="#d9a441", a="#8a5a00", h="#f6dfa0", e="#14141c"),
 px=["................",
     "................",
     "..oooooooooooo..",
     "..ohhhhhhhhhhs..",
     "..ohbbbbbbbbbs..",
     "..ohbbaaaabbbs..",
     "..ohbaaaaaabbs..",
     "..ohbaaaaaabbs..",
     "..ohbaaaaaabbs..",
     "..ohbaaaaaabbs..",
     "..ohbbaaaabbbs..",
     "..ohbbbbbbbbbs..",
     "..osssssssssss..",
     "..oooooooooooo..",
     "................",
     "................"])

S["stilus"] = dict(pal=dict(o="#2f2f38", s="#6b7186", b="#9aa0b5", a="#d7dbe6", h="#ffffff", e="#14141c"),
 px=["................",
     "............oo..",
     "...........obao.",
     "..........obbao.",
     ".........obbao..",
     "........obbao...",
     ".......obbao....",
     "......obbao.....",
     ".....obbao......",
     "....obbao.......",
     "...obbao........",
     "..obbao.........",
     "..obao..........",
     "..oao...........",
     "..oo............",
     "................"])

S["amphora"] = dict(pal=dict(o="#4a2412", s="#8a4526", b="#b5623a", a="#e0a17a", h="#f3d2b8", e="#14141c"),
 px=["................",
     "......oooo......",
     ".....obbbbo.....",
     "......obbo......",
     "....oobbbboo....",
     "..obobbbbbbobo..",
     "..obobbbbbbobo..",
     "...oobbbbbboo...",
     "...obbbbbbbbo...",
     "...obbhbbbbbo...",
     "...obbhbbbbbo...",
     "....obbbbbbo....",
     ".....obbbbo.....",
     "......obbo......",
     "......oooo......",
     "................"])

S["lucerna"] = dict(pal=dict(o="#4a3a10", s="#8a6a10", b="#d9a441", a="#fff3b0", h="#ffffff", e="#14141c"),
 px=["................",
     "................",
     "........a.......",
     ".......aha......",
     ".......aha......",
     "........a.......",
     "................",
     "....oooooooo....",
     "..oobbbbbbbboo..",
     ".obbbbbbbbbbbbo.",
     "obbbbaabbbbbbbbo",
     "obbbbaabbbbbbbbo",
     ".obbbbbbbbbbbbo.",
     "..osssssssssso..",
     "...oooooooooo...",
     "................"])

S["corona"] = dict(pal=dict(o="#26401a", s="#5a7a30", b="#8aa14f", a="#c3d99a", h="#e8f2d4", e="#14141c"),
 px=["................",
     ".......oo.......",
     ".....oo..oo.....",
     "....oao..oao....",
     "...oaao..oaao...",
     "..obao....oabo..",
     "..obao....oabo..",
     ".obao......oabo.",
     ".obao......oabo.",
     ".obbao....oabbo.",
     "..obao....oabo..",
     "..oobao..oaboo..",
     "...oobaooaboo...",
     "....oobaabooo...",
     ".....oaaaao.....",
     "......oaao......"])

S["gladius"] = dict(pal=dict(o="#26262e", s="#8a8fa0", b="#c8ccd8", a="#b87333", h="#ffffff", e="#14141c"),
 px=["................",
     ".......oo.......",
     "......ohbo......",
     "......ohbo......",
     "......ohbo......",
     "......ohbo......",
     "......ohbo......",
     "......ohbo......",
     "......ohbo......",
     "...oooooooooo...",
     "...oaaaaaaaao...",
     "...oooooooooo...",
     "......oaao......",
     "......oaao......",
     ".....oaaaao.....",
     "......oooo......"])

S["scutum"] = dict(pal=dict(o="#3a1414", s="#7a2530", b="#b23a48", a="#d9a441", h="#f0d79a", e="#14141c"),
 px=["................",
     "..oooooooooooo..",
     "..obbbbbbbbbbo..",
     "..obbbbbbbbbbo..",
     "..obbboaaobbbo..",
     "..obboaaaaobbo..",
     "..oboaahhaaobo..",
     "..oboahhhhaobo..",
     "..oboaahhaaobo..",
     "..obboaaaaobbo..",
     "..obbboaaobbbo..",
     "..obbbbbbbbbbo..",
     "..osbbbbbbbbso..",
     "...ossssssso....",
     "....oooooo......",
     "................"])

S["aquila"] = dict(pal=dict(o="#4a3a10", s="#8a6a10", b="#d9a441", a="#fff3b0", h="#ffffff", e="#14141c"),
 px=["................",
     ".......oo.......",
     "......obbo......",
     "..oo..obbo..oo..",
     ".obbooobboooobo.",
     "obbbbbbbbbbbbbbo",
     "obbbbbbbbbbbbbbo",
     ".obbbbbbbbbbbbo.",
     "..obbbbbbbbbbo..",
     "....obbbbbbo....",
     "......obbo......",
     "....oooooooo....",
     "....oaaaaaao....",
     "....oooooooo....",
     "......oaao......",
     "......oaao......"])

S["toga"] = dict(pal=dict(o="#3f3f4a", s="#b8b6c8", b="#eceaf5", a="#b23a48", h="#e0b48a", e="#14141c"),
 px=["................",
     "......oooo......",
     ".....ohhhho.....",
     ".....ohhhho.....",
     "......ohho......",
     "....oobbbboo....",
     "...obbbbbbbbso..",
     "..obbbbabbbbbso.",
     "..obhhhhabbbbso.",
     "..obbbbhabbbbso.",
     "..obbbbbabbbbso.",
     "...obbbbabbbso..",
     "...obbbbabbbso..",
     "...obbbbabbbso..",
     "...obbbbbbbbso..",
     "...oooooooooo..."])

S["delphinus"] = dict(pal=dict(o="#12283a", s="#2e5675", b="#4f7ca3", a="#a9c8de", h="#ffffff", e="#14141c"),
 px=["................",
     "................",
     ".........oo.....",
     "........obbo....",
     "...oooooobbboo..",
     "..obbbbbbbbbbbbo",
     ".obebbbbbbbbbbbo",
     "obbbbbbbbbbbbbbo",
     "obbbbbbbbbbbbboo",
     ".obbbbbbbbbbbo.o",
     "..ooobbbbbbbo..o",
     ".....ooobbbo..oo",
     "........oooo....",
     "................",
     "................",
     "................"])

S["rota"] = dict(pal=dict(o="#2a1a30", s="#523065", b="#7b4b94", a="#ffd24a", h="#f0e0ff", e="#14141c"),
 px=["................",
     "....oooooooo....",
     "..oobbbbbbbboo..",
     ".obbbbbabbbbbbo.",
     ".obbbbbabbbbbbo.",
     "obbbooobooobbbbo",
     "obbbobbbbobbbbbo",
     "oaaaabbabbaaaaao",
     "oaaaabbabbaaaaao",
     "obbbobbbbobbbbbo",
     "obbbooobooobbbbo",
     ".obbbbbabbbbbbo.",
     ".obbbbbabbbbbbo.",
     "..oobbbbbbbboo..",
     "....oooooooo....",
     "................"])

S["columna"] = dict(pal=dict(o="#4a4a55", s="#a0a4b5", b="#d7dbe6", a="#f5f7fb", h="#ffffff", e="#14141c"),
 px=["................",
     "..oooooooooooo..",
     "..oaaaaaaaaaao..",
     "..oooooooooooo..",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "....obabaobo....",
     "...oooooooooo...",
     "..oaaaaaaaaaao..",
     "..oooooooooooo..",
     "................"])

S["lupa"] = dict(pal=dict(o="#241a10", s="#5a4228", b="#8a6a45", a="#d9a441", h="#e8d0a0", e="#14141c"),
 px=["................",
     ".oo.............",
     "obbo....oooooo..",
     "obebboooobbbbbo.",
     "obbbbbbbbbbbbbbo",
     "obbbbbbbbbbbbbbo",
     ".obbbbbbbbbbbbbo",
     "..obbbbbbbbbbbbo",
     "..obbbbbbbbbbbbo",
     "..obo.obo.obo.oo",
     "..obo.obo.obo.o.",
     "..obo.obo.obo...",
     "..oo..oo..oo....",
     "................",
     "................",
     "................"])

S["navis"] = dict(pal=dict(o="#3a2412", s="#7a4526", b="#b5623a", a="#eceaf5", h="#ffffff", e="#14141c"),
 px=["................",
     ".......o........",
     ".......oaa......",
     ".......oaaaa....",
     ".......oaaaaaa..",
     ".......oaaaaaa..",
     ".......oaaaa....",
     ".......oaa......",
     ".......o........",
     ".......o........",
     "oooooooooooooooo",
     "obbbbbbbbbbbbbbo",
     ".obbbbbbbbbbbbo.",
     "..oobbbbbbbboo..",
     "....oooooooo....",
     "................"])

S["theatrum"] = dict(pal=dict(o="#3a3020", s="#a08a5a", b="#d9c9a0", a="#5a4a30", h="#f2e8d0", e="#14141c"),
 px=["................",
     "..oooooooooooo..",
     "..oaaaaaaaaaao..",
     "..oooooooooooo..",
     "..obbbbbbbbbbo..",
     "..oboobooboobo..",
     "..obeeboebeebo..",
     "..obeeboebeebo..",
     "..obbbbbbbbbbo..",
     "..oboobooboobo..",
     "..obeeboebeebo..",
     "..obeeboebeebo..",
     "..obbbbbbbbbbo..",
     "..osssssssssso..",
     "..oooooooooooo..",
     "................"])

S["serpens"] = dict(pal=dict(o="#12240f", s="#4a6a2a", b="#8aa14f", a="#ffd24a", h="#d8e8b0", e="#14141c"),
 px=["................",
     ".....oooooo.....",
     "....obbbbbbo....",
     "...obeabbbbbo...",
     "...obbbbbbbbo...",
     "...oobbbbbbo....",
     ".....obbbbo.....",
     "......obbo......",
     ".....obbbo......",
     "....obbbbo......",
     "...obbbbo.......",
     "..obbbbo........",
     "..obbbo.........",
     "..obbbboooo.....",
     "...obbbbbbbo....",
     "....oooooooo...."])

S["phoenix"] = dict(pal=dict(o="#3a1206", s="#b23a48", b="#e2664a", a="#ffd24a", h="#fff3b0", e="#14141c"),
 px=["................",
     ".......oo.......",
     "......oaao......",
     "..oo..oaao..oo..",
     ".obbo.obbo.obbo.",
     "obbbboobbooobbbo",
     "obbbbbbbbbbbbbbo",
     ".obbbbbbbbbbbbo.",
     "..obbbbbbbbbbo..",
     "...obbbbbbbbo...",
     "....obbbbbbo....",
     ".....obbbbo.....",
     "....obaaaabo....",
     "...obaaaaaabo...",
     "..oo.oo..oo.oo..",
     "................"])

S["triumphus"] = dict(pal=dict(o="#4a3a10", s="#b87333", b="#ffd24a", a="#fff3b0", h="#ffffff", e="#14141c"),
 px=["................",
     "..oooooooooooo..",
     "..oaaaaaaaaaao..",
     "..oooooooooooo..",
     "..obbbbbbbbbbo..",
     "..obbboooobbbo..",
     "..obboeeeeobbo..",
     "..oboeeeeeeobo..",
     "..oboeeeeeeobo..",
     "..oboeeeeeeobo..",
     "..oboeeeeeeobo..",
     "..oboeeeeeeobo..",
     "..oooeeeeeeooo..",
     "..oooooooooooo..",
     "..osssssssssso..",
     "................"])

S["imperium"] = dict(pal=dict(o="#3a1020", s="#7b4b94", b="#b23a48", a="#ffd24a", h="#fff3b0", e="#14141c"),
 px=["................",
     ".......a........",
     "..a...aha...a...",
     ".aha..aha..aha..",
     "..a.oooooo.a....",
     "..oooaaaaooo....",
     ".obbaaaaaabbo...",
     ".obbbaaaabbbo...",
     ".obbbbaabbbbo...",
     ".obbbbbbbbbbo...",
     ".obbbbbbbbbbo...",
     ".oaaaaaaaaaao...",
     ".obbbbbbbbbbo...",
     ".oooooooooooo...",
     "................",
     "................"])

S["mille"] = dict(pal=dict(o="#4a3a10", s="#b87333", b="#ffd24a", a="#fff3b0", h="#ffffff", e="#14141c"),
 px=["................",
     "................",
     "..oo........oo..",
     "..obo......obo..",
     "..obbo....obbo..",
     "..obabo..obabo..",
     "..obabboobabbo..",
     "..obab.oo.babo..",
     "..obab....babo..",
     "..obab....babo..",
     "..obab....babo..",
     "..obab....babo..",
     "..obab....babo..",
     "..oooo....oooo..",
     "................",
     "................"])

